# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: klima.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='klima.proto',
  package='acremote',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bklima.proto\x12\x08\x61\x63remote\"\x06\n\x04Void\"\x96\x02\n\x0cStateRequest\x12\r\n\x05power\x18\x01 \x01(\x08\x12\x13\n\x0btemperature\x18\x02 \x01(\x05\x12+\n\x05speed\x18\x03 \x01(\x0e\x32\x1c.acremote.StateRequest.Speed\x12)\n\x04mode\x18\x04 \x01(\x0e\x32\x1b.acremote.StateRequest.Mode\x12\r\n\x05swing\x18\x05 \x01(\x08\x12\x0f\n\x07ionizer\x18\x06 \x01(\x08\x12\r\n\x05turbo\x18\x07 \x01(\x08\"-\n\x05Speed\x12\x07\n\x03LOW\x10\x00\x12\x07\n\x03MID\x10\x01\x12\x08\n\x04HIGH\x10\x02\x12\x08\n\x04\x41UTO\x10\x03\",\n\x04Mode\x12\x08\n\x04\x43OOL\x10\x00\x12\x08\n\x04HEAT\x10\x01\x12\x07\n\x03\x46\x41N\x10\x02\x12\x07\n\x03\x44RY\x10\x03\"\xc9\x02\n\rStateResponse\x12\r\n\x05power\x18\x01 \x01(\x08\x12\x13\n\x0btemperature\x18\x02 \x01(\x05\x12,\n\x05speed\x18\x03 \x01(\x0e\x32\x1d.acremote.StateResponse.Speed\x12*\n\x04mode\x18\x04 \x01(\x0e\x32\x1c.acremote.StateResponse.Mode\x12\r\n\x05swing\x18\x05 \x01(\x08\x12\x0f\n\x07ionizer\x18\x06 \x01(\x08\x12\r\n\x05turbo\x18\x07 \x01(\x08\x12\x16\n\x0emaxTemperature\x18\x08 \x01(\x05\x12\x16\n\x0eminTemperature\x18\t \x01(\x05\"-\n\x05Speed\x12\x07\n\x03LOW\x10\x00\x12\x07\n\x03MID\x10\x01\x12\x08\n\x04HIGH\x10\x02\x12\x08\n\x04\x41UTO\x10\x03\",\n\x04Mode\x12\x08\n\x04\x43OOL\x10\x00\x12\x08\n\x04HEAT\x10\x01\x12\x07\n\x03\x46\x41N\x10\x02\x12\x07\n\x03\x44RY\x10\x03\x32\x82\x01\n\x0e\x41irConditioner\x12;\n\x08SetState\x12\x16.acremote.StateRequest\x1a\x17.acremote.StateResponse\x12\x33\n\x08GetState\x12\x0e.acremote.Void\x1a\x17.acremote.StateResponseb\x06proto3')
)



_STATEREQUEST_SPEED = _descriptor.EnumDescriptor(
  name='Speed',
  full_name='acremote.StateRequest.Speed',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MID', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTO', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=221,
  serialized_end=266,
)
_sym_db.RegisterEnumDescriptor(_STATEREQUEST_SPEED)

_STATEREQUEST_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='acremote.StateRequest.Mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COOL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEAT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAN', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRY', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=268,
  serialized_end=312,
)
_sym_db.RegisterEnumDescriptor(_STATEREQUEST_MODE)

_STATERESPONSE_SPEED = _descriptor.EnumDescriptor(
  name='Speed',
  full_name='acremote.StateResponse.Speed',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MID', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTO', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=221,
  serialized_end=266,
)
_sym_db.RegisterEnumDescriptor(_STATERESPONSE_SPEED)

_STATERESPONSE_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='acremote.StateResponse.Mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COOL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEAT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAN', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRY', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=268,
  serialized_end=312,
)
_sym_db.RegisterEnumDescriptor(_STATERESPONSE_MODE)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='acremote.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=31,
)


_STATEREQUEST = _descriptor.Descriptor(
  name='StateRequest',
  full_name='acremote.StateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='power', full_name='acremote.StateRequest.power', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='acremote.StateRequest.temperature', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='acremote.StateRequest.speed', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='acremote.StateRequest.mode', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='swing', full_name='acremote.StateRequest.swing', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ionizer', full_name='acremote.StateRequest.ionizer', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='turbo', full_name='acremote.StateRequest.turbo', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATEREQUEST_SPEED,
    _STATEREQUEST_MODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=312,
)


_STATERESPONSE = _descriptor.Descriptor(
  name='StateResponse',
  full_name='acremote.StateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='power', full_name='acremote.StateResponse.power', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='acremote.StateResponse.temperature', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='acremote.StateResponse.speed', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='acremote.StateResponse.mode', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='swing', full_name='acremote.StateResponse.swing', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ionizer', full_name='acremote.StateResponse.ionizer', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='turbo', full_name='acremote.StateResponse.turbo', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxTemperature', full_name='acremote.StateResponse.maxTemperature', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minTemperature', full_name='acremote.StateResponse.minTemperature', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATERESPONSE_SPEED,
    _STATERESPONSE_MODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=644,
)

_STATEREQUEST.fields_by_name['speed'].enum_type = _STATEREQUEST_SPEED
_STATEREQUEST.fields_by_name['mode'].enum_type = _STATEREQUEST_MODE
_STATEREQUEST_SPEED.containing_type = _STATEREQUEST
_STATEREQUEST_MODE.containing_type = _STATEREQUEST
_STATERESPONSE.fields_by_name['speed'].enum_type = _STATERESPONSE_SPEED
_STATERESPONSE.fields_by_name['mode'].enum_type = _STATERESPONSE_MODE
_STATERESPONSE_SPEED.containing_type = _STATERESPONSE
_STATERESPONSE_MODE.containing_type = _STATERESPONSE
DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['StateRequest'] = _STATEREQUEST
DESCRIPTOR.message_types_by_name['StateResponse'] = _STATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'klima_pb2'
  # @@protoc_insertion_point(class_scope:acremote.Void)
  })
_sym_db.RegisterMessage(Void)

StateRequest = _reflection.GeneratedProtocolMessageType('StateRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATEREQUEST,
  '__module__' : 'klima_pb2'
  # @@protoc_insertion_point(class_scope:acremote.StateRequest)
  })
_sym_db.RegisterMessage(StateRequest)

StateResponse = _reflection.GeneratedProtocolMessageType('StateResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATERESPONSE,
  '__module__' : 'klima_pb2'
  # @@protoc_insertion_point(class_scope:acremote.StateResponse)
  })
_sym_db.RegisterMessage(StateResponse)



_AIRCONDITIONER = _descriptor.ServiceDescriptor(
  name='AirConditioner',
  full_name='acremote.AirConditioner',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=647,
  serialized_end=777,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetState',
    full_name='acremote.AirConditioner.SetState',
    index=0,
    containing_service=None,
    input_type=_STATEREQUEST,
    output_type=_STATERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetState',
    full_name='acremote.AirConditioner.GetState',
    index=1,
    containing_service=None,
    input_type=_VOID,
    output_type=_STATERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AIRCONDITIONER)

DESCRIPTOR.services_by_name['AirConditioner'] = _AIRCONDITIONER

# @@protoc_insertion_point(module_scope)
